// Auto-generated by scripts/build-characters-data.mjs from the Mark character sheets.
// Do not edit by hand — re-run the script.
export type CharacterGroup = "twelve" | "key" | "faces";

export interface CharacterFact {
  text: string;
  ref: string;
}

export interface Character {
  slug: string;
  name: string;
  subtitle: string;
  image: string | null;
  caption: string;
  group: CharacterGroup;
  /** Scripture gives this person no name. */
  unnamed: boolean;
  facts: CharacterFact[];
  personality: string[];
  /** Mark chapter numbers (1-based) referenced by this character. */
  chapters: number[];
}

export const CHARACTERS: Character[] = [
  {
    "slug": "peter",
    "name": "Simon Peter",
    "subtitle": "Simon son of Jonah · The Rock",
    "image": "/images/characters/peter.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named first among the twelve",
        "ref": "Mark 3:16"
      },
      {
        "text": "Part of the inner circle: present at the raising of Jairus's daughter (Mark 5:37), the Transfiguration (Mark 9:2-8), and Gethsemane",
        "ref": "Mark 14:33"
      },
      {
        "text": "Confessed \"You are the Christ\" (Mark 8:29), then was rebuked: \"Get behind me, Satan!\"",
        "ref": "Mark 8:33"
      },
      {
        "text": "Cut off the servant's ear at Jesus's arrest",
        "ref": "John 18:10 — narrated in John, not Mark"
      }
    ],
    "personality": [
      "**Bold and impulsive** — speaks first, acts first (Mark 8:29; Mark 9:5; John 18:10)",
      "**Deeply loyal but fearful** — vowed he would never fall away, then denied Jesus (Mark 14:29-31, 14:66-72)",
      "**A natural leader** — always listed first; spokesman for the disciples (Mark 3:16; Acts 2:14)"
    ],
    "chapters": [
      3,
      5,
      8,
      9,
      14
    ]
  },
  {
    "slug": "andrew",
    "name": "Andrew",
    "subtitle": "Brother of Peter · The Connector",
    "image": "/images/characters/andrew.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve",
        "ref": "Mark 3:18"
      },
      {
        "text": "With Peter, James, and John, privately asked Jesus about the signs of the end times",
        "ref": "Mark 13:3-4"
      }
    ],
    "personality": [
      "**A connector** — every time Andrew appears in John's Gospel, he is bringing someone to Jesus (John 1:42; 6:9; 12:22)",
      "**Quiet and faithful** — never seeks the spotlight; content in the background",
      "**Practical** — assesses resources honestly (\"there is a boy here... but what are they for so many?\" — John 6:9)"
    ],
    "chapters": [
      3,
      13
    ]
  },
  {
    "slug": "james-son-of-zebedee",
    "name": "James, Son of Zebedee",
    "subtitle": "Son of Zebedee · Son of Thunder",
    "image": "/images/characters/james-son-of-zebedee.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Part of the **inner circle** with Peter and John: raising of Jairus's daughter (Mark 5:37), the Transfiguration (Mark 9:2-8), Gethsemane",
        "ref": "Mark 14:33"
      },
      {
        "text": "With John, asked Jesus for the seats of honor at his right and left in glory (Mark 10:35-40) — Jesus answered that they would drink his cup and be baptized with his baptism",
        "ref": ""
      },
      {
        "text": "With Peter, John, and Andrew, asked about the end times",
        "ref": "Mark 13:3-4"
      }
    ],
    "personality": [
      "**Zealous and intense** — \"Son of Thunder\" (Mark 3:17; Luke 9:54)",
      "**Ambitious** — sought greatness beside Jesus (Mark 10:35-40)",
      "**Courageous** — Jesus said he would indeed drink the cup of suffering (Mark 10:39)"
    ],
    "chapters": [
      5,
      9,
      10,
      13,
      14
    ]
  },
  {
    "slug": "john-son-of-zebedee",
    "name": "John, Son of Zebedee",
    "subtitle": "Son of Zebedee · The Beloved Disciple",
    "image": "/images/characters/john-son-of-zebedee.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Part of the **inner circle**: raising of Jairus's daughter (Mark 5:37), the Transfiguration (Mark 9:2-8), Gethsemane",
        "ref": "Mark 14:33"
      },
      {
        "text": "Reported a man casting out demons in Jesus's name: \"we tried to stop him, because he was not following us\" — Jesus corrected him",
        "ref": "Mark 9:38-40"
      },
      {
        "text": "With James, asked for seats of honor",
        "ref": "Mark 10:35-40"
      }
    ],
    "personality": [
      "**Transformed by love** — from \"Son of Thunder\" (Mark 3:17) to the apostle who wrote \"God is love\" (1 John 4:8)",
      "**Intimate with Jesus** — closest to him at the table and the cross (John 13:23; 19:26)",
      "**Bold in witness** — \"we cannot but speak of what we have seen and heard\" (Acts 4:20)"
    ],
    "chapters": [
      5,
      9,
      10,
      14
    ]
  },
  {
    "slug": "philip",
    "name": "Philip",
    "subtitle": "From Bethsaida · The Practical One",
    "image": "/images/characters/philip.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve apostles",
        "ref": "Mark 3:18"
      },
      {
        "text": "Scripture records no other Philip-specific moments in Mark.",
        "ref": ""
      }
    ],
    "personality": [
      "**Practical and calculating** — immediately counts the cost (John 6:7)",
      "**Literal-minded** — asks to see the Father plainly (John 14:8)",
      "**A bringer** — like Andrew, he brings others to Jesus (John 1:45; 12:22)"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "bartholomew",
    "name": "Bartholomew (Nathanael)",
    "subtitle": "Nathanael of Cana · No Deceit",
    "image": "/images/characters/bartholomew.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve as Bartholomew",
        "ref": "Mark 3:18"
      },
      {
        "text": "Scripture records no other Bartholomew-specific moments in Mark.",
        "ref": ""
      }
    ],
    "personality": [
      "**Honest and guileless** — Jesus himself testified: \"in whom there is no deceit\" (John 1:47)",
      "**Skeptical but open** — questioned Nazareth, then believed fully when confronted with truth (John 1:46-49)",
      "**A true seeker** — was under the fig tree (a traditional place of prayer and Scripture study) when Jesus saw him (John 1:48)"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "matthew",
    "name": "Matthew (Levi)",
    "subtitle": "Levi the Tax Collector · The Writer",
    "image": "/images/characters/matthew.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "His calling at the tax booth",
        "ref": "Mark 2:14"
      },
      {
        "text": "Hosted a dinner where Jesus ate with tax collectors and sinners — prompting the Pharisees' complaint and Jesus's answer: \"Those who are well have no need of a physician, but those who are sick. I came not to call the righteous, but sinners.\"",
        "ref": "Mark 2:15-17"
      },
      {
        "text": "Named among the twelve",
        "ref": "Mark 3:18"
      }
    ],
    "personality": [
      "**Decisive** — \"he rose and followed him\" (Mark 2:14); Luke adds \"he left everything\" (Luke 5:28)",
      "**Hospitable** — immediately opened his home to Jesus and his outcast friends (Mark 2:15)",
      "**Transformed outsider** — from collaborator with Rome to apostle; his Gospel bridges Jew and Gentile"
    ],
    "chapters": [
      2,
      3
    ]
  },
  {
    "slug": "thomas",
    "name": "Thomas (Didymus)",
    "subtitle": "Didymus the Twin · Honest Doubter",
    "image": "/images/characters/thomas.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve apostles",
        "ref": "Mark 3:18"
      },
      {
        "text": "Scripture records no other Thomas-specific moments in Mark.",
        "ref": ""
      }
    ],
    "personality": [
      "**Honestly skeptical** — will not pretend to believe what he does not (John 20:25)",
      "**Brave** — ready to die with Jesus (John 11:16)",
      "**Deeply devoted once convinced** — \"My Lord and my God!\" (John 20:28)"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "james-son-of-alphaeus",
    "name": "James, Son of Alphaeus",
    "subtitle": "Son of Alphaeus · James the Less",
    "image": "/images/characters/james-son-of-alphaeus.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve apostles",
        "ref": "Mark 3:18"
      },
      {
        "text": "Scripture records no other moments for him in Mark — or in any Gospel.",
        "ref": ""
      }
    ],
    "personality": [
      "Scripture gives us no words or actions of his. What we know: Jesus chose him, and he remained — named faithfully in every list (Mark 3:18; Acts 1:13). **Faithfulness without fame.**"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "thaddaeus",
    "name": "Thaddaeus (Judas Son of James)",
    "subtitle": "Judas son of James · The Questioner",
    "image": "/images/characters/thaddaeus.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve apostles",
        "ref": "Mark 3:18"
      },
      {
        "text": "Scripture records no other moments for him in Mark.",
        "ref": ""
      }
    ],
    "personality": [
      "**Thoughtful and earnest** — his one question shows a mind reaching for deeper understanding (John 14:22)",
      "**Quietly faithful** — present from the calling to the upper room (Mark 3:18; Acts 1:13)"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "simon-the-zealot",
    "name": "Simon the Zealot",
    "subtitle": "The Zealot · Fire Redirected",
    "image": "/images/characters/simon-the-zealot.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named among the twelve apostles",
        "ref": "Mark 3:18"
      },
      {
        "text": "Scripture records no other moments for him in Mark — or in any Gospel narrative.",
        "ref": ""
      }
    ],
    "personality": [
      "Scripture gives no words or actions — but his epithet speaks: this was a man of **fire and conviction**, a former revolutionary (or at least a man known for zeal) who redirected his passion to following Jesus.",
      "Consider the company he kept: Simon the Zealot and Matthew the tax collector — a Jewish nationalist and a Roman collaborator — both among the twelve. **Jesus's kingdom holds together people the world says cannot mix.**"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "judas-iscariot",
    "name": "Judas Iscariot",
    "subtitle": "Iscariot · The Tragedy",
    "image": "/images/characters/judas-iscariot.jpg",
    "caption": "",
    "group": "twelve",
    "unnamed": false,
    "facts": [
      {
        "text": "Named last among the twelve, **\"Judas Iscariot, who betrayed him\"**",
        "ref": "Mark 3:19"
      },
      {
        "text": "Went to the chief priests to betray Jesus; they promised him money, \"and he sought an opportunity to betray him\"",
        "ref": "Mark 14:10-11"
      },
      {
        "text": "At the Last Supper, Jesus said, \"Truly, I say to you, one of you will betray me, one who is eating with me\" — the disciples asked sorrowfully, \"Is it I?\"",
        "ref": "Mark 14:17-21"
      },
      {
        "text": "**Betrayed Jesus with a kiss** in Gethsemane: \"The betrayer had given them a sign, saying, 'The one I will kiss is the man. Seize him.'\"",
        "ref": "Mark 14:43-46"
      }
    ],
    "personality": [
      "**Trusted and ordinary** — one of the twelve for three years; the others did not suspect him (John 13:22, 28-29)",
      "**Secretly corrupt** — stole from the common purse (John 12:6)",
      "**Remorseful too late** — confessed his sin and returned the silver (Matt 27:3-4), but despaired instead of turning back"
    ],
    "chapters": [
      3,
      14
    ]
  },
  {
    "slug": "jesus",
    "name": "Jesus",
    "subtitle": "The Son of God · The Suffering Servant",
    "image": "/images/characters/jesus.webp",
    "caption": "",
    "group": "key",
    "unnamed": false,
    "facts": [
      {
        "text": "Forgives sins — \"the Son of Man has authority on earth to forgive sins\"",
        "ref": "Mark 2:5-10"
      },
      {
        "text": "Lord of the Sabbath",
        "ref": "Mark 2:28"
      },
      {
        "text": "Commands nature: calms the storm (Mark 4:39), walks on water",
        "ref": "Mark 6:48-51"
      },
      {
        "text": "Commands demons — they know who he is and fear him",
        "ref": "Mark 1:24; 3:11; 5:7"
      }
    ],
    "personality": [],
    "chapters": [
      1,
      2,
      4,
      6
    ]
  },
  {
    "slug": "mary-mother-of-jesus",
    "name": "Mary, Mother of Jesus",
    "subtitle": "Mother of Jesus · The Servant",
    "image": "/images/characters/mary-mother-of-jesus.jpg",
    "caption": "",
    "group": "key",
    "unnamed": false,
    "facts": [
      {
        "text": "Jesus is called **\"the son of Mary\"** by the Nazareth crowd (Mark 6:3) — an unusual formulation (men were normally identified by their fathers), possibly reflecting local knowledge or contempt",
        "ref": ""
      },
      {
        "text": "His mother and brothers came to take him, thinking **\"he is out of his mind\"**; Jesus answered, \"Whoever does the will of God, he is my brother and sister and mother.\"",
        "ref": "Mark 3:21, 3:31-35"
      },
      {
        "text": "**Note:** \"Mary the mother of James the younger and of Joses\" watched the crucifixion (Mark 15:40) and came to the tomb (Mark 16:1). Whether this is Jesus's mother is debated — many hold she is a different Mary.",
        "ref": ""
      }
    ],
    "personality": [
      "**Humble and obedient** — \"let it be to me according to your word\" (Luke 1:38)",
      "**Pondering** — \"treasured up all these things, pondering them in her heart\" (Luke 2:19, 2:51)",
      "**Courageous** — stood at the cross when the disciples fled (John 19:25)"
    ],
    "chapters": [
      3,
      6,
      15,
      16
    ]
  },
  {
    "slug": "mary-magdalene",
    "name": "Mary Magdalene",
    "subtitle": "From Magdala · First Witness",
    "image": "/images/characters/mary-magdalene.jpg",
    "caption": "",
    "group": "key",
    "unnamed": false,
    "facts": [
      {
        "text": "Watched the crucifixion from a distance with the other women",
        "ref": "Mark 15:40"
      },
      {
        "text": "Watched where Jesus was buried",
        "ref": "Mark 15:47"
      },
      {
        "text": "Came to the tomb on the first day of the week with spices — and found it empty",
        "ref": "Mark 16:1-8"
      },
      {
        "text": "**Jesus appeared to her first** after the resurrection: \"he appeared first to Mary Magdalene, from whom he had cast out seven demons\"",
        "ref": "Mark 16:9"
      }
    ],
    "personality": [
      "**Devoted** — followed Jesus from Galilee to Jerusalem, stayed at the cross when others fled (Mark 15:40-41)",
      "**Generous** — funded the ministry from her own resources (Luke 8:3)",
      "**Courageous** — first to the tomb, first to proclaim the resurrection (John 20:1, 18)"
    ],
    "chapters": [
      15,
      16
    ]
  },
  {
    "slug": "john-the-baptist",
    "name": "John the Baptist",
    "subtitle": "The Voice in the Wilderness",
    "image": "/images/characters/john-the-baptist.jpg",
    "caption": "",
    "group": "key",
    "unnamed": false,
    "facts": [
      {
        "text": "**\"The beginning of the gospel\"** opens with him: \"Behold, I send my messenger before your face\"",
        "ref": "Mark 1:1-3, quoting Mal 3:1 and Isa 40:3"
      },
      {
        "text": "Preached **\"a baptism of repentance for the forgiveness of sins\"**; crowds from Jerusalem and Judea came to him",
        "ref": "Mark 1:4-5"
      },
      {
        "text": "Proclaimed: **\"After me comes he who is mightier than I, the strap of whose sandals I am not worthy to stoop down and untie. I have baptized you with water, but he will baptize you with the Holy Spirit.\"**",
        "ref": "Mark 1:7-8"
      },
      {
        "text": "**Baptized Jesus** in the Jordan — the heavens torn open, the Spirit descending like a dove, the Father's voice: \"You are my beloved Son; with you I am well pleased.\"",
        "ref": "Mark 1:9-11"
      }
    ],
    "personality": [
      "**Fearless** — confronted Herod to his face (Mark 6:18)",
      "**Humble** — \"He must increase, but I must decrease\" (John 3:30); unworthy to untie sandals (Mark 1:7)",
      "**Uncompromising** — no flattery for crowds or kings (Matt 3:7; Mark 6:18)"
    ],
    "chapters": [
      1
    ]
  },
  {
    "slug": "pontius-pilate",
    "name": "Pontius Pilate",
    "subtitle": "Governor of Judea · The Compromise",
    "image": "/images/characters/pontius-pilate.jpg",
    "caption": "",
    "group": "key",
    "unnamed": false,
    "facts": [
      {
        "text": "Jesus was **delivered to Pilate** bound by the chief priests",
        "ref": "Mark 15:1"
      },
      {
        "text": "Pilate asked, **\"Are you the King of the Jews?\"** Jesus answered, **\"You have said so.\"**",
        "ref": "Mark 15:2"
      },
      {
        "text": "The chief priests accused Jesus of many things, but Jesus made no further answer — **\"so that Pilate was amazed\"**",
        "ref": "Mark 15:3-5"
      },
      {
        "text": "At the Passover feast, Pilate offered to release a prisoner; the crowd, stirred by the chief priests, demanded **Barabbas** — a rebel and murderer",
        "ref": "Mark 15:6-11"
      }
    ],
    "personality": [
      "**Politically calculating** — knew Jesus was handed over out of envy (Mark 15:10; Matt 27:18), yet chose the crowd over justice (Mark 15:15)",
      "**Morally uneasy** — amazed by Jesus's silence (Mark 15:5); warned by his wife's dream (Matt 27:19); tried to release him (John 19:12)",
      "**Ultimately weak** — \"wishing to satisfy the crowd\" (Mark 15:15); the man with the power who surrendered it"
    ],
    "chapters": [
      15
    ]
  },
  {
    "slug": "barabbas",
    "name": "Barabbas",
    "subtitle": "The Prisoner Set Free",
    "image": "/images/characters/barabbas.jpg",
    "caption": "A real man, not a monster — which is what makes the exchange so staggering.",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "It was Pilate's custom at the feast to **release one prisoner** for the crowd",
        "ref": "Mark 15:6"
      },
      {
        "text": "Pilate offered the crowd a choice: \"Do you want me to release to you the King of the Jews?\" — hoping to free Jesus",
        "ref": "Mark 15:9"
      },
      {
        "text": "The chief priests **stirred up the crowd** to ask for Barabbas instead",
        "ref": "Mark 15:11"
      },
      {
        "text": "\"What then do you want me to do with him whom you call the King of the Jews?\" — \"Crucify him!\"",
        "ref": "Mark 15:12-13"
      }
    ],
    "personality": [
      "**Violent** — a murderer in an armed uprising (Mark 15:7)",
      "**Popular** — the crowd chose him over Jesus (Mark 15:11)",
      "**The exchanged** — the guilty went free; the innocent took his cross (Mark 15:15)"
    ],
    "chapters": [
      15
    ]
  },
  {
    "slug": "bartimaeus",
    "name": "Bartimaeus",
    "subtitle": "The Blind Beggar of Jericho",
    "image": "/images/characters/bartimaeus.jpg",
    "caption": "Shown here after receiving his sight — following Jesus on the way (Mark 10:52).",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Hearing it was Jesus of Nazareth, **he began to cry out**: \"Jesus, Son of David, have mercy on me!\" (Mark 10:47) — calling him the Messiah's title",
        "ref": ""
      },
      {
        "text": "Many **rebuked him, telling him to be silent** — \"but he cried out all the more, 'Son of David, have mercy on me!'\"",
        "ref": "Mark 10:48"
      },
      {
        "text": "Jesus stopped and said, \"Call him.\" They told him, \"Take heart. Get up; he is calling you\"",
        "ref": "Mark 10:49"
      },
      {
        "text": "**Throwing off his cloak** — his only possession, his beggar's license — he sprang up and came to Jesus",
        "ref": "Mark 10:50"
      }
    ],
    "personality": [
      "**Persistent** — would not be silenced, cried out \"all the more\" (Mark 10:48)",
      "**Theologically bold** — a blind beggar confessing Jesus as \"Son of David\" while the crowds just said \"Jesus of Nazareth\" (Mark 10:47)",
      "**Decisive** — threw off his cloak before he was healed, staking everything on Jesus (Mark 10:50)"
    ],
    "chapters": [
      10
    ]
  },
  {
    "slug": "herod-antipas",
    "name": "Herod Antipas",
    "subtitle": "Tetrarch of Galilee · The Divided King",
    "image": "/images/characters/herod-antipas.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Heard about Jesus and feared he was **John the Baptist raised from the dead** — \"John, whom I beheaded, has been raised\" (Mark 6:14-16). His guilty conscience spoke.",
        "ref": ""
      },
      {
        "text": "Others said Jesus was Elijah or a prophet like the prophets of old; Herod insisted: **\"John, whom I beheaded, has been raised\"**",
        "ref": "Mark 6:15-16"
      },
      {
        "text": "**Imprisoned John** for saying, \"It is not lawful for you to have your brother's wife\"",
        "ref": "Mark 6:17-18"
      },
      {
        "text": "**\"Herod feared John, knowing that he was a righteous and holy man, and he kept him safe. When he heard him, he was greatly perplexed, and yet he heard him gladly\"** (Mark 6:20) — a divided man, drawn to the truth yet unwilling to obey it",
        "ref": ""
      }
    ],
    "personality": [
      "**Conscience-stricken but weak** — he knew John was righteous, heard him gladly, yet caved to pressure (Mark 6:20, 26)",
      "**Proud** — would not break a rash oath before his guests, even to commit murder (Mark 6:26)",
      "**Superstitious** — haunted by the thought that John had risen (Mark 6:16)"
    ],
    "chapters": [
      6
    ]
  },
  {
    "slug": "herodias",
    "name": "Herodias",
    "subtitle": "The Grudge",
    "image": "/images/characters/herodias.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Her marriage to Antipas was condemned by John the Baptist: **\"It is not lawful for you to have your brother's wife\"**",
        "ref": "Mark 6:18"
      },
      {
        "text": "**\"Herodias had a grudge against him and wanted to put him to death\"** — but she could not, because Herod protected John",
        "ref": "Mark 6:19"
      },
      {
        "text": "At Herod's birthday banquet, her daughter danced and pleased Herod; when the girl asked her mother what to request, Herodias answered: **\"The head of John the Baptist\"**",
        "ref": "Mark 6:22-25"
      },
      {
        "text": "The head was brought on a platter and given to the girl, who gave it to her mother",
        "ref": "Mark 6:28"
      }
    ],
    "personality": [
      "**Resentful** — nursed a grudge against the man who told the truth about her marriage (Mark 6:19)",
      "**Ruthless** — used her own daughter as the instrument of murder (Mark 6:24-25)",
      "**Calculating** — waited for \"an opportune time\" — Herod's birthday, with all the powerful men of Galilee present (Mark 6:21)"
    ],
    "chapters": [
      6
    ]
  },
  {
    "slug": "jairus",
    "name": "Jairus",
    "subtitle": "Synagogue Leader · A Father's Plea",
    "image": "/images/characters/jairus.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Seeing Jesus, **he fell at his feet and implored him earnestly**: \"My little daughter is at the point of death. Come and lay your hands on her, so that she may be made well and live\" (Mark 5:22-23) — a synagogue ruler humbling himself publicly",
        "ref": ""
      },
      {
        "text": "On the way, messengers came: **\"Your daughter is dead. Why trouble the Teacher any further?\"**",
        "ref": "Mark 5:35"
      },
      {
        "text": "Jesus answered: **\"Do not fear, only believe\"**",
        "ref": "Mark 5:36"
      },
      {
        "text": "Jesus took only Peter, James, and John — and the child's parents — into the house",
        "ref": "Mark 5:37, 40"
      }
    ],
    "personality": [
      "**Humble** — a man of status who fell at Jesus's feet in front of a crowd (Mark 5:22)",
      "**Persistent in faith** — kept believing after the worst news a father can hear (Mark 5:35-36)",
      "**Obedient** — did exactly as Jesus directed, bringing only whom Jesus chose (Mark 5:37-40)"
    ],
    "chapters": [
      5
    ]
  },
  {
    "slug": "joseph-of-arimathea",
    "name": "Joseph of Arimathea",
    "subtitle": "Council Member · The Bold Burial",
    "image": "/images/characters/joseph-of-arimathea.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "After Jesus died, **\"he took courage and went to Pilate and asked for the body of Jesus\"** (Mark 15:43) — going to the Roman governor as a council member took courage; the Sanhedrin had just condemned Jesus",
        "ref": ""
      },
      {
        "text": "Pilate was surprised Jesus was already dead; he summoned the centurion, confirmed it, and granted the body to Joseph",
        "ref": "Mark 15:44-45"
      },
      {
        "text": "Joseph bought a linen shroud, took him down, wrapped him, **laid him in a tomb cut out of the rock**, and rolled a stone against the entrance",
        "ref": "Mark 15:46"
      },
      {
        "text": "**Mary Magdalene and Mary the mother of Joses saw where he was laid**",
        "ref": "Mark 15:47"
      }
    ],
    "personality": [
      "**Courageous** — stepped forward when the disciples had fled (Mark 15:43)",
      "**Devout** — \"looking for the kingdom of God\" even from inside the council (Mark 15:43)",
      "**Generous** — gave his own tomb for the Lord (Mark 15:46; Matt 27:60)"
    ],
    "chapters": [
      15
    ]
  },
  {
    "slug": "salome",
    "name": "Salome, Daughter of Herodias",
    "subtitle": "Daughter of Herodias",
    "image": "/images/characters/salome.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "At Herod's birthday banquet, **she came in and danced, and she pleased Herod and his guests**",
        "ref": "Mark 6:22"
      },
      {
        "text": "Herod swore to her: **\"Whatever you ask me, I will give you, up to half of my kingdom\"**",
        "ref": "Mark 6:23"
      },
      {
        "text": "She went out and said to her mother, **\"What shall I ask?\"** — Herodias answered, \"The head of John the Baptist\"",
        "ref": "Mark 6:24"
      },
      {
        "text": "She came in immediately with haste and said, **\"I want you to give me at once the head of John the Baptist on a platter\"**",
        "ref": "Mark 6:25"
      }
    ],
    "personality": [
      "**Young** — a girl dancing at a banquet, asking her mother what to wish for (Mark 6:22, 24)",
      "**Used** — her mother turned a dance into a murder (Mark 6:24-25)",
      "**A tragedy, not a villainess** — Scripture shows a young woman caught in her mother's scheme, not its author"
    ],
    "chapters": [
      6
    ]
  },
  {
    "slug": "salome-wife-of-zebedee",
    "name": "Salome, Wife of Zebedee",
    "subtitle": "Wife of Zebedee · Mother of James and John",
    "image": "/images/characters/salome-wife-of-zebedee.jpg",
    "caption": "Not the daughter of Herodias — a different Salome entirely: the mother of James and John.",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Stood watching the crucifixion **\"from a distance\"** with Mary Magdalene and Mary the mother of James the younger — the women who stayed when the men fled",
        "ref": "Mark 15:40"
      },
      {
        "text": "Came to the tomb **\"very early on the first day of the week\"** with Mary Magdalene and Mary the mother of James, bringing spices to anoint Jesus",
        "ref": "Mark 16:1-2"
      },
      {
        "text": "Found the stone rolled away and heard the young man say, \"He has risen\"",
        "ref": "Mark 16:4-6"
      }
    ],
    "personality": [
      "**Devoted** — followed Jesus to the cross and to the tomb (Mark 15:40; 16:1)",
      "**Ambitious for her sons** — wanted the best for James and John (Matt 20:20-21)",
      "**Faithful** — among the last at the cross and the first at the tomb (Mark 15:40; 16:1)"
    ],
    "chapters": [
      15,
      16
    ]
  },
  {
    "slug": "simon-of-cyrene",
    "name": "Simon of Cyrene",
    "subtitle": "From Cyrene · He Carried the Cross",
    "image": "/images/characters/simon-of-cyrene.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "As Jesus, beaten and exhausted, carried his cross to Golgotha, the soldiers **\"compelled a passerby, Simon of Cyrene, who was coming in from the country, the father of Alexander and Rufus, to carry his cross\"**",
        "ref": "Mark 15:21"
      },
      {
        "text": "He carried the cross of the Son of God — the only person in history to do so",
        "ref": ""
      }
    ],
    "personality": [
      "**Unwilling at first, honored forever** — compelled, not volunteered (Mark 15:21)",
      "**A father whose sons were known** — his family became part of the church's story (Mark 15:21; Rom 16:13, per tradition)"
    ],
    "chapters": [
      15
    ]
  },
  {
    "slug": "boy-evil-spirit",
    "name": "The Boy Freed from the Evil Spirit",
    "subtitle": "The Boy at the Mountain's Foot",
    "image": "/images/characters/boy-evil-spirit.jpg",
    "caption": "Scripture does not give his name. A father's only son — and Jesus's answer to \"if you can.\"",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "His father brought him to the disciples while Jesus was on the mountain — **they could not cast it out**",
        "ref": "Mark 9:17-18"
      },
      {
        "text": "Jesus: **\"O faithless generation, how long shall I be with you?\"**",
        "ref": "Mark 9:19"
      },
      {
        "text": "The boy was brought to Jesus; the spirit convulsed him, and he **fell on the ground, wallowing and foaming**",
        "ref": "Mark 9:20"
      },
      {
        "text": "\"How long has this been happening to him?\" — **\"From childhood\"**",
        "ref": "Mark 9:21"
      }
    ],
    "personality": [
      "Scripture tells us little of the boy himself — his story is his father's faith and Jesus's compassion (Mark 9:17-27)",
      "**Restored** — lifted by the hand of Jesus, he arose (Mark 9:27)"
    ],
    "chapters": [
      9
    ]
  },
  {
    "slug": "centurion-at-cross",
    "name": "The Centurion at the Cross",
    "subtitle": "The Soldier Who Saw",
    "image": "/images/characters/centurion-at-cross.jpg",
    "caption": "Scripture does not give his name. A Roman soldier — and the first person in Mark's Gospel to confess who Jesus is.",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Stood facing Jesus through the crucifixion — the darkness, the cry of dereliction, the final breath",
        "ref": "Mark 15:33-37"
      },
      {
        "text": "**Saw how he breathed his last** — not just that he died, but *how*: the manner of his death undid him",
        "ref": "Mark 15:39"
      },
      {
        "text": "Confessed: **\"Truly this man was the Son of God!\"** (Mark 15:39) — the only human confession of Jesus's divine sonship in Mark's Gospel comes from a Gentile executioner",
        "ref": ""
      }
    ],
    "personality": [
      "**Observant** — he watched, and what he saw changed him (Mark 15:39)",
      "**Honest** — a professional executioner who spoke the truth at personal risk (Mark 15:39)",
      "**The first confessor** — in Mark's Gospel, demons confessed Jesus (Mark 1:24; 5:7), Peter confessed him (Mark 8:29) — but this Gentile soldier is the climactic human voice (Mark 15:39)"
    ],
    "chapters": [
      15
    ]
  },
  {
    "slug": "deaf-mute-decapolis",
    "name": "The Deaf and Mute Man of Decapolis",
    "subtitle": "“Ephphatha” — Be Opened",
    "image": "/images/characters/deaf-mute-decapolis.jpg",
    "caption": "Scripture does not give his name. A Gentile in the Decapolis — and the word \"Ephphatha.\"",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "Jesus came through the Decapolis — the region of the Gerasene demoniac he had freed",
        "ref": "Mark 7:31; 5:20"
      },
      {
        "text": "They **brought him to Jesus and begged him to lay his hand on him**",
        "ref": "Mark 7:32"
      },
      {
        "text": "Jesus **took him aside from the multitude, privately** — away from the crowd",
        "ref": "Mark 7:33"
      },
      {
        "text": "He **put his fingers into his ears**, spat, and **touched his tongue**",
        "ref": "Mark 7:33"
      }
    ],
    "personality": [
      "Scripture tells us little of the man himself — but his neighbors' love brought him to Jesus (Mark 7:32)",
      "**Healed gently** — taken aside privately, touched with tenderness (Mark 7:33)"
    ],
    "chapters": [
      7
    ]
  },
  {
    "slug": "gerasene-demoniac",
    "name": "The Gerasene Demoniac",
    "subtitle": "The Man from the Tombs · First Missionary",
    "image": "/images/characters/gerasene-demoniac.jpg",
    "caption": "Shown here after his healing — clothed and in his right mind (Mark 5:15).",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "Jesus cast the legion of demons out of him; they entered a herd of about **two thousand pigs**, which rushed down the steep bank into the sea and drowned",
        "ref": "Mark 5:11-13"
      },
      {
        "text": "The townspeople came and found him **\"sitting there, clothed and in his right mind\"** — and they were afraid",
        "ref": "Mark 5:15"
      },
      {
        "text": "He **begged Jesus to let him go with him** — but Jesus said: **\"Go home to your friends and tell them how much the Lord has done for you, and how he has had mercy on you\"**",
        "ref": "Mark 5:18-19"
      },
      {
        "text": "**He obeyed** — \"he went away and began to proclaim in the Decapolis how much Jesus had done for him, and everyone marveled\"",
        "ref": "Mark 5:20"
      }
    ],
    "personality": [
      "**Grateful** — his first impulse was to stay with Jesus (Mark 5:18)",
      "**Obedient** — when told to go home instead, he went (Mark 5:20)",
      "**The first missionary to the Gentiles** — sent to proclaim Christ in the Decapolis before any apostle was"
    ],
    "chapters": [
      5
    ]
  },
  {
    "slug": "withered-hand",
    "name": "The Man with the Withered Hand",
    "subtitle": "Healed on the Sabbath",
    "image": "/images/characters/withered-hand.jpg",
    "caption": "Scripture does not give his name. Healed on the Sabbath — in front of everyone watching.",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "He was in the **synagogue on the Sabbath** when Jesus entered",
        "ref": "Mark 3:1"
      },
      {
        "text": "The Pharisees **watched him closely** — \"whether he would heal him on the Sabbath, so that they might accuse him\"",
        "ref": "Mark 3:2"
      },
      {
        "text": "Jesus said to the man, **\"Step forward\"** — into the center, before them all",
        "ref": "Mark 3:3"
      },
      {
        "text": "Then to the watchers: **\"Is it lawful on the Sabbath to do good or to do evil, to save life or to kill?\"** — But they were silent",
        "ref": "Mark 3:4"
      }
    ],
    "personality": [
      "**Courageous** — he stepped into the center when called (Mark 3:3)",
      "**Obedient** — \"stretch out your hand\" — the impossible command, obeyed (Mark 3:5)"
    ],
    "chapters": [
      3
    ]
  },
  {
    "slug": "paralytic-roof",
    "name": "The Paralytic Lowered Through the Roof",
    "subtitle": "Lowered Through the Roof",
    "image": "/images/characters/paralytic-roof.jpg",
    "caption": "Scripture does not give his name. Four friends, a crowded house, and a roof torn open.",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "Jesus was preaching in a house in **Capernaum** — the crowd was so thick \"there was no room, not even at the door\"",
        "ref": "Mark 2:1-2"
      },
      {
        "text": "His four friends **could not get near Jesus** because of the crowd — so they went up on the roof, **removed the roof above him, and let down the bed**",
        "ref": "Mark 2:4"
      },
      {
        "text": "Jesus **\"saw their faith\"** — the faith of the friends — and said to the paralytic, **\"Son, your sins are forgiven\"**",
        "ref": "Mark 2:5"
      },
      {
        "text": "The scribes reasoned in their hearts: \"Who can forgive sins but God alone?\"",
        "ref": "Mark 2:6-7"
      }
    ],
    "personality": [
      "**Helped** — he had four friends who would tear open a roof for him (Mark 2:3-4)",
      "**Forgiven first** — before his legs were healed, his soul was (Mark 2:5)",
      "**Obedient** — when told to rise, he rose (Mark 2:12)"
    ],
    "chapters": [
      2
    ]
  },
  {
    "slug": "poor-widow",
    "name": "The Poor Widow",
    "subtitle": "Two Small Coins · The Greatest Gift",
    "image": "/images/characters/poor-widow.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "Jesus sat opposite the treasury and watched the crowd putting money in; **many rich people put in large sums**",
        "ref": "Mark 12:41"
      },
      {
        "text": "She came and **put in two small copper coins** — *lepta*, the smallest coins in circulation — **\"which make a penny\"**",
        "ref": "Mark 12:42"
      },
      {
        "text": "Jesus called his disciples and said: **\"Truly, I say to you, this poor widow has put in more than all those who are contributing to the offering box\"**",
        "ref": "Mark 12:43"
      },
      {
        "text": "**\"For they all contributed out of their abundance, but she out of her poverty has put in everything she had, all she had to live on\"**",
        "ref": "Mark 12:44"
      }
    ],
    "personality": [
      "**Faithful** — gave when she had every excuse not to (Mark 12:42)",
      "**Trusting** — gave \"all she had to live on,\" leaving her future entirely to God (Mark 12:44)",
      "**Unseen by all but Jesus** — no one else noticed; heaven did (Mark 12:41-43)"
    ],
    "chapters": [
      12
    ]
  },
  {
    "slug": "rich-young-ruler",
    "name": "The Rich Young Ruler",
    "subtitle": "The One Who Walked Away",
    "image": "/images/characters/rich-young-ruler.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "**Ran up and knelt before Jesus**: \"Good Teacher, what must I do to inherit eternal life?\" (Mark 10:17) — earnest, humble, urgent",
        "ref": ""
      },
      {
        "text": "Jesus answered: \"Why do you call me good? No one is good except God alone\" (Mark 10:18) — pointing him to who Jesus is",
        "ref": ""
      },
      {
        "text": "He listed the commandments; the man said, \"Teacher, all these I have kept from my youth\"",
        "ref": "Mark 10:19-20"
      },
      {
        "text": "**\"And Jesus, looking at him, loved him\"** — the only person in the Gospels of whom this is said",
        "ref": "Mark 10:21"
      }
    ],
    "personality": [
      "**Earnest** — ran, knelt, asked the most important question (Mark 10:17)",
      "**Sincere** — Jesus did not dispute his claim to have kept the commandments (Mark 10:20-21)",
      "**Loved by Jesus** — looked at with love even in the moment of refusal (Mark 10:21)"
    ],
    "chapters": [
      10
    ]
  },
  {
    "slug": "scribe-greatest-commandment",
    "name": "The Scribe Who Asked About the Greatest Commandment",
    "subtitle": "“Not Far from the Kingdom”",
    "image": "/images/characters/scribe-greatest-commandment.jpg",
    "caption": "Scripture does not give his name. A scribe who asked honestly — and heard he was not far from the kingdom.",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "He had **heard the Sadducees disputing with Jesus** and saw that Jesus \"answered them well\"",
        "ref": "Mark 12:28"
      },
      {
        "text": "He asked: **\"Which is the first commandment of all?\"**",
        "ref": "Mark 12:28"
      },
      {
        "text": "Jesus answered: **\"The first of all the commandments is: 'Hear, O Israel, the Lord our God, the Lord is one. And you shall love the Lord your God with all your heart, with all your soul, with all your mind, and with all your strength.' This is the first commandment. And the second, like it, is this: 'You shall love your neighbor as yourself.' There is no other commandment greater than these\"**",
        "ref": "Mark 12:29-31"
      },
      {
        "text": "The scribe answered **wisely**: \"Well said, Teacher. You have spoken the truth... to love him with all the heart... and to love one's neighbor as oneself, is more than all the whole burnt offerings and sacrifices\"",
        "ref": "Mark 12:32-33"
      }
    ],
    "personality": [
      "**Honest** — he asked to learn, not to trap (Mark 12:28)",
      "**Wise** — he understood that love outweighs ritual (Mark 12:33)",
      "**Near** — \"not far from the kingdom of God\" — the closest any religious leader comes in Mark (Mark 12:34)"
    ],
    "chapters": [
      12
    ]
  },
  {
    "slug": "syrophoenician-woman",
    "name": "The Syrophoenician Woman",
    "subtitle": "A Gentile Mother's Faith",
    "image": "/images/characters/syrophoenician-woman.jpg",
    "caption": "",
    "group": "faces",
    "unnamed": false,
    "facts": [
      {
        "text": "Hearing of Jesus, she came and **fell down at his feet** and begged him to cast the demon out of her daughter",
        "ref": "Mark 7:25-26"
      },
      {
        "text": "Jesus said, \"Let the children be fed first, for it is not right to take the children's bread and throw it to the dogs\" (Mark 7:27) — testing her faith",
        "ref": ""
      },
      {
        "text": "She answered: **\"Yes, Lord; yet even the dogs under the table eat the children's crumbs\"** (Mark 7:28) — one of the humblest and boldest answers in Scripture",
        "ref": ""
      },
      {
        "text": "He said to her, **\"For this statement you may go your way; the demon has left your daughter\"**",
        "ref": "Mark 7:29"
      }
    ],
    "personality": [
      "**Desperate in love** — a mother's love drove her past every barrier (Mark 7:25-26)",
      "**Humble** — accepted the hard word without offense (Mark 7:28)",
      "**Quick-witted in faith** — turned Jesus's own metaphor into her plea (Mark 7:28)"
    ],
    "chapters": [
      7
    ]
  },
  {
    "slug": "woman-with-issue-of-blood",
    "name": "The Woman with the Issue of Blood",
    "subtitle": "Healed After Twelve Years",
    "image": "/images/characters/woman-with-issue-of-blood.jpg",
    "caption": "Shown here after her healing — whole, at peace (Mark 5:34).",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "Hearing about Jesus, she came up behind him in the crowd and **touched his garment** — \"For she said, 'If I touch even his garments, I will be made well'\"",
        "ref": "Mark 5:27-28"
      },
      {
        "text": "**Immediately** her flow of blood dried up, and she felt in her body that she was healed",
        "ref": "Mark 5:29"
      },
      {
        "text": "Jesus, perceiving power had gone out from him, asked, \"Who touched my garments?\"",
        "ref": "Mark 5:30"
      },
      {
        "text": "She came **\"in fear and trembling\"** and fell down before him and told him the whole truth",
        "ref": "Mark 5:33"
      }
    ],
    "personality": [
      "**Desperate but believing** — after twelve years and every earthly hope exhausted, she still believed (Mark 5:25-28)",
      "**Humble** — came secretly, from behind; did not demand, only touched (Mark 5:27)",
      "**Honest** — when asked, she told \"the whole truth\" (Mark 5:33)"
    ],
    "chapters": [
      5
    ]
  },
  {
    "slug": "young-man-fled",
    "name": "The Young Man Who Fled",
    "subtitle": "Gethsemane · The One Who Ran",
    "image": "/images/characters/young-man-fled.jpg",
    "caption": "Scripture does not give his name. Only Mark records him — two verses, and then he is gone.",
    "group": "faces",
    "unnamed": true,
    "facts": [
      {
        "text": "When Jesus was arrested in Gethsemane and **\"they all forsook him and fled\"**",
        "ref": "Mark 14:50"
      },
      {
        "text": "A young man followed, **\"having a linen cloth thrown around his naked body\"** — roused from sleep, grabbing the nearest covering",
        "ref": "Mark 14:51"
      },
      {
        "text": "The soldiers **seized him** — and he left the linen cloth behind and **ran away naked**",
        "ref": "Mark 14:52"
      }
    ],
    "personality": [
      "**Curious** — he followed when the disciples fled (Mark 14:51)",
      "**Frightened** — when seized, he ran (Mark 14:52)",
      "**Human** — the most relatable figure in the arrest scene: brave enough to follow, scared enough to run (Mark 14:51-52)"
    ],
    "chapters": [
      14
    ]
  }
];

export const CHARACTER_GROUPS: { id: CharacterGroup; title: string; blurb: string }[] = [
  {
    id: "twelve",
    title: "The Twelve",
    blurb: "The men Jesus chose and sent — ordinary fishermen, a tax collector, a revolutionary, and one who would betray Him.",
  },
  {
    id: "key",
    title: "Key Figures",
    blurb: "The people at the center of Mark's Gospel — and those who stood in judgment over Him.",
  },
  {
    id: "faces",
    title: "Faces of Mark",
    blurb: "Everyone else Mark introduces — rulers and beggars, the healed and the hurting. Every one of them met Jesus.",
  },
];

export function getCharacter(slug: string): Character | undefined {
  return CHARACTERS.find((c) => c.slug === slug);
}

export function unnamedCharacters(): Character[] {
  return CHARACTERS.filter((c) => c.unnamed);
}
